egovernments/municipal-services

build/build-config.yml

update build-config.yml for bpa-services changes

update build-config.yml for bpa-services changes

---

build/build-config.yml

bpa-caculator build configuration

bpa-caculator build configuration

---

bpa-services/src/main/java/org/egov/bpa/service/notification/BPANotificationService.java
bpa-services/src/main/java/org/egov/bpa/service/notification/PaymentNotificationService.java
bpa-services/src/main/java/org/egov/bpa/util/NotificationUtil.java
bpa-services/src/main/java/org/egov/bpa/web/models/Action.java
bpa-services/src/main/java/org/egov/bpa/web/models/ActionItem.java
bpa-services/src/main/java/org/egov/bpa/web/models/EventDetails.java
bpa-services/src/main/java/org/egov/bpa/web/models/Recepient.java
bpa-services/src/main/java/org/egov/bpa/web/models/Source.java
bpa-services/src/main/resources/application.properties

Changes in the notifications for testing.

Bpa mseva notif

---

bpa-services/src/main/java/org/egov/bpa/validator/BPAValidator.java

Validating the multiple report for field inspection

Multiple FI report validation

---

bpa-services/src/main/resources/application.properties

bihar edcr url change

---

tl-services/src/main/resources/db/migration/main/V202004221013334__tl_add_filestoreid_ddl.sql

adding filestoreid to tradelicense audit table

adding filestoreid to tradelicense audit table

---

bpa-services/src/main/java/org/egov/bpa/service/EnrichmentService.java

unit fix in bihar dev to merge to prod

---

property-services/src/main/java/org/egov/pt/repository/AssessmentRepository.java
property-services/src/main/java/org/egov/pt/repository/PropertyRepository.java
property-services/src/main/java/org/egov/pt/service/AssessmentService.java
property-services/src/main/java/org/egov/pt/service/PropertyService.java
property-services/src/main/resources/db/migration/main/V20200519183640__add_eg_pt_asmt_assessment_indexes.sql

Property endpoint update added search parameters in bulk search endpoints

---

bpa-calculator/CHANGELOG.md
bpa-calculator/pom.xml
bpa-calculator/src/main/resources/application.properties
bpa-services/CHANGELOG.md
bpa-services/pom.xml
bpa-services/src/main/resources/application.properties

maven upgrade to bpa-services following the document
https://digit-discuss.atlassian.net/wiki/spaces/EPE/pages/487096370/Maven+version+upgrade

Spring version upgrade changes

---

build/build-config.yml

added noc bulid config

---

bpa-services/src/main/java/org/egov/bpa/service/notification/BPANotificationService.java

OAP-599,OAP-600
Notifications to Architect are not sent .

Fixed only stakeholder should receive the message .

---

noc-services/pom.xml

OAP-635 Corrected version number from 0.0.1 to 1.0.0

OAP-635 Corrected version number

---

bpa-calculator/LOCALSETUP.md
bpa-calculator/README.md
bpa-services/LOCALSETUP.md
bpa-services/README.md
docs/bpa/bpa-calculator.yaml
docs/bpa/bpa-service.yaml
land-services/LOCALSETUP.md
land-services/README.md
noc-services/LOCALSETUP.md
noc-services/README.md

Added read me and local setup for bpa-calculator,bpa-services,noc-services and land-services

OAP-635 : Added read me and local setup for bpa-calculator,bpa-services,noc-services and land-services

---

land-services/README.md

OAP-635 Updated readme of land-services by adding API contract

OAP-635 Updated readme of land-services by adding API contract

---

bpa-services/README.md

OAP-635 Updated readme of bpa-services by adding API contract and dependencies

OAP-635 Updated readme of bpa-services by adding API contract and dependencies

---

build/build-config.yml

Update build-config.yaml for fsm and fsm-calculator services

FSM-74 (added)  build config for fsm and fsm-calculator

---

bpa-services/CHANGELOG.md
bpa-services/pom.xml

OAP-648 Updated version and changelog

OAP-648 Updated version and changelog

---

fsm/src/main/resources/db/migration/main/V202128190950.1__fix.sql

FSM-88 Missing columns fix

---

build/build-config.yml

FSM-88 vendor and vehicle build config

FSM-88 vendor and vehicle build config

---

bpa-services/src/main/java/org/egov/bpa/service/EnrichmentService.java
bpa-services/src/main/java/org/egov/bpa/service/UserService.java
bpa-services/src/main/java/org/egov/bpa/util/BPAConstants.java

Set assignee to workflow when send to citizen/stakeholder

OAP-654 set assignee to workflow when send to citizen/stakeholder

---

tl-services/src/main/java/org/egov/tl/service/TradeLicenseService.java

Update additional details in update TL api

Update additionalDetail in update TL API

---

bpa-services/src/main/java/org/egov/bpa/service/EnrichmentService.java

When send to architect add only architect uuid in the assignee

OAP-654 When send to architect add only architect uuid in the assignee

---

bpa-services/src/main/java/org/egov/bpa/service/EnrichmentService.java

On citizen approve set assignee to stakeholder

OAP-654 On citizen approve set assignee to stakeholder

---

bpa-services/src/main/java/org/egov/bpa/util/BPAConstants.java

OAP-654 Update missing constants

---

fsm-calculator/src/main/java/org/egov/fsm/calculator/services/CalculationService.java
fsm/src/main/java/org/egov/fsm/repository/FSMRepository.java
fsm/src/main/java/org/egov/fsm/repository/querybuilder/FSMQueryBuilder.java
fsm/src/main/java/org/egov/fsm/repository/rowmapper/FSMAuditRowMapper.java
fsm/src/main/java/org/egov/fsm/repository/rowmapper/FSMRowMapper.java
fsm/src/main/java/org/egov/fsm/service/FSMService.java
fsm/src/main/java/org/egov/fsm/service/PaymentUpdateService.java
fsm/src/main/java/org/egov/fsm/service/VehicleTripService.java
fsm/src/main/java/org/egov/fsm/util/FSMAuditUtil.java
fsm/src/main/java/org/egov/fsm/util/FSMConstants.java
fsm/src/main/java/org/egov/fsm/util/FSMToFSMAuditUtilConverter.java
fsm/src/main/java/org/egov/fsm/validator/FSMValidator.java
fsm/src/main/java/org/egov/fsm/web/controller/FSMController.java
fsm/src/main/java/org/egov/fsm/web/model/FSMResponse.java

Fsm dev v2

---

docs/fsm/Fsm_Apply_Contract.yaml
docs/fsm/Vehicle_Registry_Contract.yaml
fsm-calculator/README.md
fsm/src/main/java/org/egov/fsm/service/FSMService.java
vehicle/README.md
vendor/README.md

possible service date and documentation fixes

possible service date and documentation fixes

---

build/build-config.yml

fixed buildconfig for fsm,fsm-calculator,vendor,vehicle

fixed buildconfig for fsm,fsm-calculator,vendor,vehicle

---

fsm/pom.xml
fsm/src/main/java/org/egov/fsm/repository/querybuilder/FSMAuditQueryBuilder.java
fsm/src/main/java/org/egov/fsm/repository/rowmapper/FSMAuditRowMapper.java
fsm/src/main/resources/workflowconfig.json
vehicle/pom.xml
vendor/pom.xml

logic to identify the unique data from the rowmapper (#704)
base version to 1.0.0

Modified the query to feth data from auditlogs and also removed

---

fsm/src/main/resources/workflowconfig.json

updated workflow config removing unnecessary actions

updated workflow config removing unnecessary actions

---

fsm/src/main/resources/workflowconfig.json

udpate workflowconfig removing actions not needed

udpate workflowconfig removing actions not needed

---

fsm/src/main/java/org/egov/fsm/service/FSMService.java
fsm/src/main/java/org/egov/fsm/util/FSMErrorConstants.java
fsm/src/main/java/org/egov/fsm/web/model/FSM.java
fsm/src/main/resources/db/migration/main/V20210803121555.1__compledtedon.sql
fsm/src/main/resources/fsm-persister.yaml

* base version to 1.0.0
* tenantid changed from pb.amritsar to pb
tenantid changed from pb.amritsar to pb
#	fsm/src/main/resources/workflowconfig.json

base version to 1.0.0 (#706)

---

bpa-calculator/pom.xml

RAIN-2223 Upgarded POM version

RAIN-2223 Upgarded POM version

---

docs/fsm/Fsm_Apply_Contract.yaml
fsm/CHANGELOG.md
fsm/src/main/java/org/egov/fsm/repository/rowmapper/FSMRowMapper.java
fsm/src/main/java/org/egov/fsm/service/FSMService.java
fsm/src/main/java/org/egov/fsm/util/FSMConstants.java
fsm/src/main/java/org/egov/fsm/workflow/WorkflowIntegrator.java
fsm/src/main/resources/application.properties
fsm/src/main/resources/workflowconfig.json

FSM-299, 295,298

---

fsm/src/main/java/org/egov/fsm/service/FSMService.java
fsm/src/main/resources/application.properties

DSO Search and Paylink are fixed

DSO Search and Paylink

---

fsm/src/main/java/org/egov/fsm/config/FSMConfiguration.java
fsm/src/main/java/org/egov/fsm/service/FSMService.java
fsm/src/main/java/org/egov/fsm/service/PaymentUpdateService.java
fsm/src/main/java/org/egov/fsm/util/NotificationUtil.java
fsm/src/main/java/org/egov/fsm/validator/FSMValidator.java
fsm/src/main/resources/application.properties

Cherry pick of commits from 18th March till date from master branch

Cherry pick of commits from 18th March till date from master branch

---

build/build-config.yml

RAIN-2391 Build changes for turn-io-adapter service

RAIN-2391 Build changes for turn-io-adapter service

---

noc-services/pom.xml

(cherry picked from commit f2e921662387d16bcced516f1596f2446a0d1df9)

RAIN-2442 NOC crashloopback fixes

---

fsm/src/main/resources/workflowconfig.json

FSM UAT removed decline action in dso_inprogress status

removed decline action in dso_inprogress status

---

fsm/pom.xml
fsm/src/main/java/org/egov/fsm/service/PaymentUpdateService.java
fsm/src/main/java/org/egov/fsm/service/notification/NotificationService.java
fsm/src/main/java/org/egov/fsm/util/FSMErrorConstants.java
fsm/src/main/java/org/egov/fsm/util/FSMUtil.java
fsm/src/main/java/org/egov/fsm/util/NotificationUtil.java
fsm/src/main/java/org/egov/fsm/validator/FSMValidator.java
fsm/src/main/java/org/egov/fsm/validator/MDMSValidator.java
fsm/src/main/java/org/egov/fsm/web/model/FSM.java
fsm/src/main/java/org/egov/fsm/web/model/FSMRequest.java
fsm/src/main/java/org/egov/fsm/web/model/location/Address.java
fsm/src/main/resources/db/migration/main/V20210420113423.1__address_change.sql

FSM 375,376

---

fsm/src/main/java/org/egov/fsm/util/NotificationUtil.java

SMS Localization keywords changed from <> to {}.
updating the code accordingly

SMS Localization keywords changed from <> to {}.

---

fsm/src/main/java/org/egov/fsm/repository/FSMRepository.java
fsm/src/main/java/org/egov/fsm/repository/querybuilder/FSMQueryBuilder.java
fsm/src/main/java/org/egov/fsm/service/FSMService.java
fsm/src/main/java/org/egov/fsm/web/controller/FSMController.java
vehicle/src/main/java/org/egov/vehicle/repository/VehicleRepository.java
vehicle/src/main/java/org/egov/vehicle/repository/querybuilder/QueryBuilder.java
vehicle/src/main/java/org/egov/vehicle/service/VehicleService.java
vehicle/src/main/java/org/egov/vehicle/trip/controller/VehicleTripController.java
vehicle/src/main/java/org/egov/vehicle/trip/querybuilder/VehicleTripQueryBuilder.java
vehicle/src/main/java/org/egov/vehicle/trip/repository/VehicleTripRepository.java
vehicle/src/main/java/org/egov/vehicle/trip/service/VehicleTripService.java
vehicle/src/main/java/org/egov/vehicle/web/controller/VehicleController.java
vendor/src/main/java/org/egov/vendor/repository/VendorRepository.java
vendor/src/main/java/org/egov/vendor/repository/querybuilder/VendorQueryBuilder.java
vendor/src/main/java/org/egov/vendor/service/VendorService.java
vendor/src/main/java/org/egov/vendor/web/controller/VendorController.java

Plain Search for FSM,Vehicle , VehicleTrip and Vendor

Plain Search for FSM,Vehicle , VehicleTrip and Vendor

---

inbox/src/main/java/org/egov/inbox/service/InboxService.java
inbox/src/main/java/org/egov/inbox/service/WorkflowService.java
inbox/src/main/java/org/egov/inbox/util/PTConstants.java

Reverts egovernments/municipal-services#897

Revert "[RAIN-3173] Enabled employees to search applications that are non act…"
